version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install boto3

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - chmod 755 ./make_zipfile.sh
      - ./make_zipfile.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "remove except -.py"
      - rm buildspec.yml *.zip *.sh *.md
artifacts:
  files:
    - '**/*'