version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install boto3

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ./make_zipfile.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./lambda.zip